# Generated by Django 3.2 on 2021-05-29 16:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('id', models.CharField(max_length=16)),
                ('discount', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
            options={
                'db_table': 'discount',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('identification', models.CharField(max_length=16, null=True)),
                ('discount', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=10, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
            ],
            options={
                'db_table': 'guests',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_number', models.IntegerField(primary_key=True, serialize=False)),
                ('bed', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double')], default='Single', max_length=6)),
                ('ac', models.BooleanField(default=False)),
                ('token', models.IntegerField(default=-1)),
                ('occupied', models.BooleanField(default=False)),
                ('occupied_when', models.DateTimeField(default=None, null=True)),
                ('days', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('advance', models.BooleanField(default=False)),
                ('book_when', models.DateTimeField(default=None, null=True)),
                ('book_days', models.IntegerField(default=0)),
                ('advance_price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('occupancy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('usertype', models.IntegerField(choices=[(0, 'Administrator'), (1, 'Receptionist'), (2, 'Catering Service Manager')], default=1)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=16)),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.guest')),
            ],
            options={
                'db_table': 'catering',
            },
        ),
    ]
