# Generated by Django 3.2 on 2021-05-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='book_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
