# Generated by Django 3.2 on 2021-05-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bed',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double')], default='single', max_length=6),
        ),
    ]
