# Generated by Django 3.2 on 2021-05-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210529_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catering',
            name='token',
            field=models.IntegerField(default=-1),
        ),
    ]
